spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customerDB01?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.neu.springboot.provider.entities
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: user-provider1
info.app.name: provider
info.company.name: neusoft
info.author.name: ykp
logging:
  level:
    root: INFO
